name: Test

on:
  workflow_dispatch:
    inputs:
      deploy_cluster:
        description: 'Deploy the Kubernetes cluster for testing'
        required: true
        default: 'true'

jobs:
  setup_kubernetes:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Minikube status
        run: |
         $statusHost = $response | ConvertFrom-Json | Select-Object -ExpandProperty host
         $statusKubelet = $response | ConvertFrom-Json | Select-Object -ExpandProperty kubelet
         $statusApiserver = $response | ConvertFrom-Json | Select-Object -ExpandProperty apiserver
    
         if ($statusHost -ne $desired -or $statusKubelet -ne $desired -or $statusApiserver -ne $desired) {
         Exit 1
         }
        
      - name: Install Helm chart
        run: |
         cd helm/task1
         helm install task1 .
         
      - name: Wait for pod
        run: |
          $ready_pods = 0
          while ($ready_pods -lt 1) {
          $ready_pods = kubectl get deployment "task1" -o jsonpath='{.status.readyReplicas}'
          Write-Host "Waiting for pods to be ready... (Ready pods: $ready_pods)"
          Start-Sleep -Seconds 10
          }

      - name: Curl to the app
        run: |
          curl http://minikubeip.com/
          curl http://minikubeip.com/healthcheck
          try {
            curl http://notminikubeip.com/
            Write-Host "Request to $url was succssesful"
            Exit 1
          } catch {
            Write-Host "Request to url failed"
          }

      - name: Uninstall helm chart
        run: |
          helm uninstall task1
